src/core/activity/plotPanels/CVISIHistogramPanel.ts
src/core/activity/plotPanels/activityGraphPanel.ts
src/core/activity/plotPanels/analogSignalHistogramPanel.ts
src/core/activity/plotPanels/analogSignalPlotPanel.ts
src/core/activity/plotPanels/inputAnalogSignalPlotPanel.ts
src/core/activity/plotPanels/interSpikeIntervalHistogramPanel.ts
src/core/activity/plotPanels/neuronAnalogSignalPlotPanel.ts
src/core/activity/plotPanels/spikeSendersHistogramPanel.ts
src/core/activity/plotPanels/spikeTimesHistogramPanel.ts
src/core/activity/plotPanels/spikeTimesPanel.ts
src/core/activity/plotPanels/spikeTimesRasterPlotPanel.ts

This PR updates the code structure of activity panels.

Activity panel

---

src/core/parameter/parameter.ts

This PR undo code changes in params.

Fix param visibility

---

README.md
docs/about/abstract.rst

This updates the references and adds some cleanup in the lincence section.

Doc: Update References/License sections of Readme

---

src/components/model/ModelDocumentation.vue

Add link button to official user documentation of NEST Simulator

Add link to official model directory of nest-simulator

---

src/components/network/NetworkParamsEdit.vue

NetworkParamsEdit: Fix spacing issue

---

src/core/network/networkGraph.ts

NetworkGraph: Fix ESlint issue

---

src/components/activity/ActivityGraph.vue
src/components/network/NetworkGraph.vue
src/components/node/NodeMenu.vue

This PR fixes the width of node menu and make button better visible in snackbar.

Node menu snackbar button

---

src/core/activity/activityGraph.ts
src/core/connection/connection.ts
src/core/network/network.ts
src/core/node/node.ts
src/core/project/project.ts

This PR fix bug in activity graph. 
In the bug, it doesn't show any activity graph when constructing network from the sketch (without model selection).

Optimize initializing activity graph

---

package.json
src/components/project/ProjectMenu.vue
src/components/project/ProjectsDialog.vue
src/components/project/ProjectsImportDialog.vue
src/components/project/ProjectsLoadDialog.vue
src/components/project/ProjectsMenu.vue
src/components/project/ProjectsUploadDialog.vue
yarn.lock

This PR allows user to import projects from github repo (nest-desktop/nest-desktop-projects).
Plus the term (download/upload) of projects is renamed to export/import.
The doc is updated in other branch (https://github.com/babsey/nest-desktop/tree/projects-import-export-doc).

Upload project from GitHub

---

package.json
src/components/About.vue

This PR adds debug information to the mail skeleton which is created when clicking on the contact name. This should help to have basic but important information at hand without any further mail communication being necessary.

About.vue: Optimize mail text with debug information

---

package.json
src/App.vue
src/components/About.vue
src/core/backends/backend.ts
src/core/backends/nest.ts
src/views/Settings.vue

In the following, I consider a situation where the connection to the NEST Server was checked (and worked), but suddenly stopped working and is checked again. Checking the NEST Server (in the settings) leaves the green chip indicating a correct connection instead of giving some sort of error notification. This PR addresses this problem, introducing some necessary changes in the connection to the server.

Optimize check nest server

---

src/App.vue
src/components/About.vue
src/components/parameter/ParameterEdit.vue
src/core/backends/backend.ts
src/core/backends/nest.ts
src/views/Settings.vue

Addressing #69, his PR adds a notification when small resolution values are selected. I think we should not forbid these values, in case a user needs them, but instead give a warning, so that the user is aware of that risk.

Simulation Time Resolution Notification

---

LICENSE
README.md
bin/nest-desktop
docker-compose.yml
singularity/nest-desktop-app.def
singularity/nest-desktop-dev.def
singularity/nest-desktop-prod.def

This PR clarifies the name convention of NEST Desktop as GUI and NEST Simulator with API server as back end.

Rename NEST Simulator

---

docs/user/setup.rst

I think we have a small error in the docs regarding the Docker setup - I failed when running the command without `sudo`. I have also added some small optimizations.

Small Fixes for Documentation

---

docs/about/abstract.rst

This PR fixes links in abstract on readthedocs.

Doc abstract link

---

src/components/navigation/Navigation.vue
src/views/Home.vue
src/views/Project.vue

Adjusted left sidebar to 100% size while keeping the right one at the current size

Sidebars: Optimize view

---

src/core/connection/connectionCode.ts

This PR fixes the bug that the connection specification is not displayed in the simulation code.

Fix code generation for connection specifications.

---

src/components/network/NetworkGraph.vue

This PR fixes transforming network graph in network editor.

Fix transform network-graph after sidebar closing/opening

---

src/App.vue
src/assets/models/hh_psc_alpha.json
src/assets/models/multimeter.json
src/assets/models/voltmeter.json
src/components/model/ModelDocumentation.vue
src/components/model/ModelEditor.vue
src/components/model/ModelExplorer.vue
src/components/network/NetworkGraphToolbar.vue
src/components/network/NetworkParamEdit.vue
src/components/node/NodeModelSelect.vue
src/components/node/NodeParamEdit.vue
src/components/parameter/ParameterEdit.vue
src/components/simulation/SimulationKernel.vue
src/core/model/model.ts
src/core/node/node.ts
src/core/node/nodeView.ts
src/core/parameter/modelParameter.ts
src/core/parameter/parameter.ts
src/views/Model.vue

This PR includes several features:

Extend model and parameter views

---

package.json
src/components/model/ModelExplorer.vue
src/components/network/NetworkParamEdit.vue
yarn.lock

This PR upgrades node modules.

Node modules

---

src/core/network/networkCode.ts
src/core/project/projectCode.ts
src/core/simulation/simulationCode.ts

This PR updates code generation for NEST 3.1

Sim code for NEST 3.1

---

docs/lecturer/doctorate/networks-decision-making.rst
docs/user/troubleshooting.rst
docs/user/usage.rst

This PR updates documentation for project export/import.

Rename download/upload to export/import

---

src/components/navigation/Navigation.vue
src/views/Project.vue

This PR has better resizing behavior when user drags it below minimum width.

Better resizing when minimum width is set

---

src/core/model/model.ts

This PR fixes a bug, that the model component failed to lookup value defaults of a model.

Fix looking for model defaults

---

src/components/navigation/Navigation.vue
src/views/Model.vue
src/views/Project.vue

This PR adds option to have dark mode of navigation sidebar.
It replaces button toggle by tabs.

Nav dark tabs

---

src/assets/config/NodeSlice.json
src/components/connection/ConnectionMenu.vue
src/components/connection/ConnectionParamEdit.vue
src/components/connection/ConnectionParamSelect.vue
src/components/network/NetworkParamEdit.vue
src/components/node/NodeMenu.vue
src/components/node/NodeModelSelect.vue
src/components/node/NodePopMenu.vue
src/components/parameter/ParameterEdit.vue
src/components/synapse/SynapseModelSelect.vue
src/components/synapse/SynapseParamSelect.vue
src/core/connection/connection.ts
src/core/connection/connectionCode.ts
src/core/connection/connectionGraph/connectionGraph.ts
src/core/network/network.ts
src/core/node/node.ts
src/core/node/nodeSlice.ts
src/core/parameter/parameter.ts
src/core/synapse/synapse.ts

It adds a feature to slice (source/target) node for the connection.

Add node slicing

---

.github/workflows/ebrains-push.yml

This PR enables mirroring of repository on gitlab.

Add config file for mirroring repo to gitlab

---

src/components/model/ModelDocumentation.vue

This PR shows title from model ID if no response from `api/help` and tag for synapse.

Add tag for synapse and show title

---

public/index.html
vue.config.js

This PR generates page title from the `vue.config.js`

Page title

---

docs/conf.py

The PR optimize configuration for docs.
It shows warning text when using the latest version.

Change config for docs

---

src/components/model/ModelEditor.vue
src/components/parameter/ParameterEdit.vue
src/core/activity/activityAnimation/activityAnimationScenes/activityAnimationSceneBox.ts
src/core/activity/activityAnimation/activityAnimationScenes/activityAnimationSceneSphere.ts
src/core/activity/activityChart/activityChartPanelModel.ts
src/core/activity/analogSignalActivity.ts
src/core/common/database.ts
src/core/connection/connection.ts
src/core/connection/connectionState.ts
src/core/model/model.ts
src/core/network/networkGraph/networkGraphDragline.ts
src/core/network/networkState.ts
src/core/node/node.ts
src/core/node/nodeSlice.ts
src/core/node/nodeState.ts
src/core/project/projectUpgrade.ts
src/core/synapse/synapse.ts
src/views/Project.vue

The PR corrects un-/equal operator to null/undefined.

Operator to null/undefined

---

.gitlab-ci.yml
nest_desktop/__init__.py
package.json

The PR induces the beta stage of the current development.

Change version to beta

---

src/components/activity/activityChart/ActivityChartController.vue
src/components/activity/activityStats/ActivityStats.vue
src/components/connection/ConnectionParamEdit.vue
src/components/network/NetworkParamEdit.vue
src/components/project/ProjectLabBook.vue
src/components/simulation/SimulationKernel.vue

This PR restyles the card border in the controller.
Before it looks ugly because of rounded component of card.

Restyle card border in controller

---

src/core/connection/connection.ts
src/core/node/nodeSlice.ts

This PR adds node slicing in connection json which can be loaded in connection components.

Node Slice to JSON

---

docs/contents.rst
docs/user/index.rst
docs/user/usage-insite.rst

Add doc for insite

---

src/core/project/project.ts
src/core/project/projectStore.ts
src/views/Project.vue

This PR fixes creating new project when the url is provided in the address bar, e.g. 
```
http://localhost:8001/#/project?from=https://raw.githubusercontent.com/nest-desktop/nest-desktop-projects/main/simple_neuron_models/psc_time_constants.json
```

Project from url

---

src/components/connection/ConnectionMenu.vue
src/components/network/NetworkParamEdit.vue
src/components/node/NodeModelSelect.vue
src/components/simulation/SimulationCodeEditor.vue
src/components/synapse/SynapseModelSelect.vue
src/core/connection/connection.ts
src/core/connection/connectionGraph/connectionGraph.ts
src/core/node/node.ts
src/core/project/project.ts
src/core/project/projectCode.ts

This PR shows shortId or shortHash for development mode.

Use shortHash or shortId

---

package.json
vue.config.js
yarn.lock

Upgrade node modules and remove console.log in vue.config

Upgrade node modules; remove console.log in vue.config

---

package.json
src/core/activity/activityAnimation/activityAnimationScene.ts
yarn.lock

Remove `dat.gui` because of security risk

Remove dat.gui

---

src/components/CodeMirror.vue
src/components/simulation/SimulationCodeEditor.vue
src/core/project/projectView.ts
src/views/Project.vue

I like to see the doc data from the database as well as the JSON output of the project object.

Rename ProjectRawData to CodeMirror

---

package.json
src/components/navigation/Navigation.vue
yarn.lock

Upgrade node modules; remove app from nav-drawer

Upgrade node modules

---

src/components/activity/ActivityGraph.vue
src/components/activity/ActivityGraphIcon.vue
src/components/activity/activityChart/ActivityChartController.vue
src/components/activity/activityChart/ActivityChartPanelToolbar.vue
src/components/navigation/Navigation.vue
src/components/navigation/ProjectNavList.vue
src/components/project/ProjectsDialog.vue
src/components/project/ProjectsMenu.vue
src/core/activity/activityChart/activityChartGraph.ts
src/core/project/project.ts
src/core/project/projectStore.ts
src/views/Project.vue

It will not initialized project on page loading, instead it initializes project only when selected.
It might shorten loading time (See #41).

Lazy loading of projects

---

docs/deployer/deploy-insite.rst
docs/developer/continuous-integration.rst

Docs about CI und deployment of Insite

---

.gitignore

Gitignore: Add package-lock.json

---

.gitlab-ci.yml
electron-builder.yml
package.json
singularity/ubuntu-nest-desktop-dev.def
vue.config.js

This PR adds config file for electron-builder.

Better config for electron-builder

---

.gitlab-ci.yml
singularity/ubuntu-nest-desktop-dev.def

The PR fixes errors in building electron in GitLab CI.

Build electron in GitLab CI.

---

.gitlab-ci.yml

Use electronuserland/builder:wine to build electron

---

.gitlab-ci.yml

Correct VERSION

---

.gitlab-ci.yml

Last attempt to upload snap on GitLab CI.

docker-runner for snap

---

docs/contents.rst
docs/developer/coding-conventions.rst

Adding our - currently informal - conventions to the docs.

Doc: Introducing the first coding conventions

---

.gitlab-ci.yml

This PR shortens expire duration to prevent full storage on GitLab.

Shorten expire duration for electron artifacts

---

src/components/activity/activityStats/ActivityStatsAnalog.vue

This PR resolves stats table of analog activity.

Remove condition to show node record selected for table

---

.github/workflows/ebrains-push.yml

Update the name so that it becomes a bit more self-explanatory for externals

Github-Workflow: Update name for ebrains-push.yml

---

src/components/activity/activityChart/ActivityChartController.vue
src/components/node/NodeModelSelect.vue
src/components/node/NodeParamEdit.vue
src/components/parameter/ParameterEdit.vue
src/core/activity/activityChart/activityChartPanelModel.ts
src/core/activity/activityChart/activityChartPanelModels/analogSignalPanelModel.ts
src/core/common/database.ts
src/core/node/node.ts
src/core/node/nodeRecord.ts
src/core/project/projectStore.ts

Update node record.

---

src/components/node/NodePosition.vue

It restyle the popup for node positions.

Style panel for node positions

---

src/components/node/NodePopMenu.vue

Change button style for deleting node

---

docker-compose.yml

Correct port-binding for nest-desktop service in Docker Compose

Correct port-binding for nest-desktop service

---

src/core/activity/activityChart/activityChartGraph.ts
src/core/activity/activityChart/activityChartPanelModel.ts
src/core/activity/activityGraph.ts
src/core/connection/connection.ts
src/core/network/network.ts
src/core/node/node.ts

This PR fixes several bugs that did not show any activity when created new project.
It also addresses for reversing connection, deleting connection/node and changing recording models.

Fix initializing activity graph for connection/model changes.

---

.dockerignore
.gitignore
.gitlab-ci.yml
docker/Dockerfile
docker/Dockerfile-builder
docker/nginx-default.conf
nest_desktop/__init__.py

This PR renames the folder for docker files and use `nginx:stable-alpine` as base image.

Enhance docker

---

docker/Dockerfile
docker/Dockerfile-builder
docker/entrypoint.sh
public/config.json
src/App.vue
src/assets/codemirror/addon/hint/pyNEST-hint.js
src/assets/config/InsiteAccess.json
src/assets/config/NESTSimulator.json
src/components/setting/InsiteAccessConfig.vue
src/components/setting/NESTSimulatorConfig.vue
src/core/activity/analogSignalActivity.ts
src/core/activity/spikeActivity.ts
src/core/app.ts
src/core/common/backend.ts
src/core/model/model.ts
src/core/model/modelStore.ts
src/core/model/modelView.ts
src/core/project/project.ts
src/main.ts
src/shims-vue.d.ts

Add axios instances, combineURLS and slash suffix in URL for Insite

---

src/core/activity/activityChart/activityChartGraph.ts
src/core/activity/activityChart/activityChartPanelModel.ts
src/core/activity/activityChart/activityChartPanelModels/CVISIHistogramModel.ts
src/core/activity/activityChart/activityChartPanelModels/FICurvePlotModel.ts
src/core/activity/activityChart/activityChartPanelModels/analogSignalHistogramModel.ts
src/core/activity/activityChart/activityChartPanelModels/analogSignalPlotModel.ts
src/core/activity/activityChart/activityChartPanelModels/interSpikeIntervalHistogramModel.ts
src/core/activity/activityChart/activityChartPanelModels/senderCVISIPlotModel.ts
src/core/activity/activityChart/activityChartPanelModels/senderMeanISIPlotModel.ts
src/core/activity/activityChart/activityChartPanelModels/senderSpikeCountPlotModel.ts
src/core/activity/activityChart/activityChartPanelModels/spikeTimesHistogramModel.ts
src/core/activity/activityChart/activityChartPanelModels/spikeTimesRasterPlotModel.ts

This PRs stores the visiblilty of each traces/dots that the plot shows the same traces after the simulation.

Add events for plot visiblity

---

src/components/activity/activityChart/ActivityChartGraph.vue
src/core/activity/activityChart/activityChartGraph.ts

The activity chart shows wrong display when it is resized,e.g. open/close/resize sidenav.

Fix showing correct activity chart when resizing

---

package.json
src/assets/config/ProjectView.json
src/components/activity/ActivityGraph.vue
src/components/simulation/SimulationButton.vue
src/components/simulation/SimulationCodeEditor.vue
src/core/network/networkCode.ts
src/core/node/nodeCode.ts
src/core/project/project.ts
src/core/project/projectCode.ts
src/core/project/projectUpgrade.ts
src/core/project/projectView.ts
src/views/Model.vue
src/views/Project.vue
yarn.lock

This PR adds toolbar for code editor that allows users to

Add toolbar for code editor and download codes

---

src/assets/config/App.json
src/core/app.ts
src/views/Settings.vue

This PR allows users to change check interval of backends.

Add an option to change the interval of the backend checks

---

src/components/activity/activityStats/ActivityStats.vue

This PR fixes scroll behavior in activity stats.

Fix scroll behavior in activity stats

---

src/core/common/backend.ts

This PR fixes wrong cropping of backend urls.
Closes #349

Fix the cropping problem with backend URLs

---

src/components/network/NetworkEditor.vue
src/core/model/modelGraph/modelAssignGraph.ts

This PR add graph to show assigned connection to weight recorder.

Add marker for assigned connection

---

src/components/activity/activityChart/ActivityChartGraph.vue
src/core/activity/activityChart/activityChartGraph.ts
src/core/activity/activityChart/activityChartPanelModels/spikeTimesRasterPlotModel.ts

It displays markers in raster plot in more neuroscientific design.

Use other marker style for spike raster plot

---

src/core/simulation/simulationCodes/nest3.0.code
src/core/simulation/simulationCodes/nest3.1.code
src/core/simulation/simulationCodes/nest3.2.code
src/core/simulation/simulationCodes/nest3.3.code

Fix wrong implementing `record_to` in all nodes.

Fix `record_to` in simulation code

---

src/core/simulation/simulation.ts

Use time = 0 for simulation with Insite for NRP.

Fix simulation time problem (for Insite with NRP)

---

src/components/synapse/SynapseParamEdit.vue
src/core/synapse/synapse.ts

Shows receptor types only when it is provided.

Show only receptor types if provided

---

src/components/connection/ConnectionParamEdit.vue
src/components/parameter/ParameterEdit.vue
src/components/simulation/SimulationKernel.vue

Better call of the function `paramChange`.

Better call param changes

---

src/views/Settings.vue

Add hint that a page reload is required

Settings: Improve the explanatory text as mentioned in #340

---

src/components/activity/activityChart/ActivityChartController.vue

This bug disables all panel types for adding new ones.

Correct name for graph panels

---

src/assets/config/Connection.json
src/assets/config/NetworkGraph.json
src/assets/config/Node.json
src/core/connection/connectionGraph/connectionGraphPath.ts

It removes obsolete configurations from assets and increases distance of connection endpoint (arrow) to target node.

Network graph cleanup

---

docs/developer/coding-conventions.rst
docs/reference/sections/project.rst

Update the heading part of the coding conventions and a heading formatting

Fix minor flaws

---

src/core/activity/activityChart/activityChartPanelModels/analogSignalPlotModel.ts

This PR fixed the correct displaying active marker (black line) in corresponding panel and not in all panels.

Display active marker in correct panel

---

src/App.vue
src/components/dialog/ModelsDialog.vue
src/components/dialog/ModelsImportDialog.vue
src/components/dialog/ProjectsDialog.vue
src/components/dialog/ProjectsImportDialog.vue
src/components/navigation/ModelMenu.vue
src/components/navigation/ModelNavList.vue
src/components/navigation/Navigation.vue
src/components/navigation/ProjectMenu.vue
src/components/navigation/ProjectNavList.vue
src/components/network/NetworkParamToolbar.vue
src/components/simulation/SimulationCodeEditor.vue
src/components/systembar/ProjectsMenu.vue
src/core/app.ts
src/core/model/modelDB.ts
src/core/model/modelStore.ts
src/core/model/modelView.ts
src/core/network/network.ts
src/core/project/project.ts
src/core/project/projectDB.ts
src/core/project/projectState.ts
src/core/project/projectStore.ts
src/core/project/projectView.ts
src/views/AppInfo.vue
src/views/Project.vue

This PR adds button bars for project and model list.
It makes the management better accessible for users.

[Big Bang] Adding nav toolbar

---

src/core/simulation/simulation.ts

Fix toast notification when error message appears.
Additionally, a click event handler opens the user documentation in a new tab.

Fix toast notification.

---

src/components/navigation/ProjectNavList.vue

This PR shows project version in the project list when the project is not loaded yet.

Show project version in dev mode

---

.gitlab-ci.yml

Remove backticks from gitlab CI file.
Closes #420.

Remove backticks from gitlab CI file

---

src/components/node/NodeModelSelect.vue

This PR fixes wrong display of parameter labels in multicompartmental model.

NEST-specific param label

---

src/components/dialog/ModelsDialog.vue
src/components/dialog/ProjectsDialog.vue
src/core/model/modelDB.ts
src/core/model/modelStore.ts
src/core/project/projectDB.ts
src/core/project/projectStore.ts
src/core/upgrades/upgrades.ts

This PR fixes the bug whether the user cannot delete a list of projects.

Fix the bulk deletion of projects

---

src/components/simulation/SimulationCodeEditor.vue
src/core/simulation/simulationCodes/nest3.0.code
src/core/simulation/simulationCodes/nest3.1.code
src/core/simulation/simulationCodes/nest3.2.code
src/core/simulation/simulationCodes/nest3.3.code

This PR fixes simulation code generation and relocates selection input for NEST version.

Fix simulation code

---

src/components/setting/NESTSimulatorConfig.vue
src/core/app.ts
src/core/common/backend.ts
src/main.ts

This PR changes default port for NEST Server

Change default port for NEST Server

---

src/assets/config/Connection.json
src/assets/config/Node.json
src/assets/models/ac_generator.json
src/assets/models/dc_generator.json
src/assets/models/hh_psc_alpha.json
src/assets/models/iaf_cond_alpha.json
src/assets/models/iaf_psc_alpha.json
src/assets/models/multimeter.json
src/assets/models/noise_generator.json
src/assets/models/parrot_neuron.json
src/assets/models/poisson_generator.json
src/assets/models/spike_generator.json
src/assets/models/spike_recorder.json
src/assets/models/static_synapse.json
src/assets/models/step_current_generator.json
src/assets/models/voltmeter.json
src/components/network/NetworkParamEdit.vue
src/components/node/NodePosition.vue
src/components/parameter/ParameterEdit.vue
src/components/simulation/SimulationKernel.vue
src/core/app.ts

This PR fixes value validation for input forms e.g. slider, text-field.

Fix param validation

---

src/App.vue
src/components/activity/ActivityGraph.vue
src/components/activity/activityAnimation/ActivityAnimationGraph.vue
src/components/dialog/ModelsImportDialog.vue
src/components/dialog/ProjectsImportDialog.vue
src/components/simulation/SimulationButton.vue
src/views/Project.vue

Cleanup codes

---

.gitlab-ci.yml
package.json
src/assets/config/InsiteAccess.json
src/assets/config/NESTSimulator.json
src/components/setting/InsiteAccessConfig.vue
src/components/setting/NESTSimulatorConfig.vue
src/components/systembar/BackendStatus.vue
src/core/app.ts
src/core/common/backend.ts
src/main.ts
src/views/AppSettings.vue

This PR cleans up the backend:
- it can disable backend if not provided, e.g. insite.
- input rules for validation of correct url

Cleanup backends

---

src/components/systembar/BackendStatus.vue

This PR fixes bug that models are not fetched after user click on backend status check.

Fix fetching models from NEST

---

src/core/app.ts
src/core/common/config.ts
src/environments/environment.prod.ts
src/environments/environment.ts
vue.config.js

Use the environment VUE_APP_VERSION to get current version.

Use environment variable for VERSION

---

src/components/navigation/ModelNavList.vue
src/components/navigation/ProjectNavList.vue

Because of long list of models (and projects) it lags on rendering all items. 
To solve this lagging issue, we use virtual scroll that renders only visible items.

Use virtual scroll for nav list

---

src/components/navigation/ProjectNavList.vue
src/components/systembar/ProjectsMenu.vue

This PR adds item in project menu for new project.

Add `new project` in menu

---

src/components/activity/activityChart/ActivityChartController.vue
src/components/model/ModelEditor.vue
src/components/navigation/Navigation.vue
src/components/network/NetworkParamToolbar.vue
src/components/node/NodeParamEdit.vue
src/components/simulation/SimulationCodeEditor.vue
src/views/AppInfo.vue
src/views/AppSettings.vue
src/views/Model.vue
src/views/Project.vue

This PR removes v-tooltip that we can have a consistence of title popup.

Remove tooltip

---

src/components/navigation/ModelNavList.vue
src/components/systembar/BackendStatus.vue
src/components/systembar/ModelsMenu.vue
src/components/systembar/ProjectsMenu.vue

This PR improves the title texts.

Improve titles

---

src/components/parameter/ParameterEdit.vue

This PR fixes wrong incrementing and decrementing values (keyword: javascript and string).

Fix bug of value inrement/decrement

---

src/components/activity/ActivityGraph.vue
src/views/Project.vue

This PR removes help popup in model view.

No help popup in model view

---

src/components/node/NodeMenu.vue
vue.config.js

This PR fixes a small styling issue and introduces the option to activate HTTPS and HTTP/2 on the dev server,

Fix style for NodeMenu and add option to activate HTTPS + HTTP/2 on dev server

---

src/components/parameter/ParameterEdit.vue
src/core/parameter/parameter.ts

Fix bug, when user change value in input field.

Fix error whether it is a string

---

src/core/activity/activityAnimation/activityAnimationScene.ts

This PR fixes error when use resize of activityAnimGraph, i.e. open/close sidebar.

Fix clientWidth in anim graph

---

docs/about/releases.rst
package.json

Update version for the release v3.4

---

src/components/network/NetworkParamEdit.vue
src/components/node/NodeAnnotations.vue
src/core/network/network.ts
src/core/network/networkState.ts
src/core/node/node.ts
src/core/simulation/simulationCode.ts
src/core/simulation/simulationCodes/nest-v3.4.code

This PR implements node annotation which can be used for `nest.userdict`.

Introduce node annotation

---

src/components/connection/ConnectionParamEdit.vue
src/components/simulation/SimulationCodeEditor.vue
src/core/connection/connection.ts
src/core/connection/connectionParameter.ts
src/core/connection/connectionRule.ts
src/core/connection/connectionView.ts
src/core/network/network.ts
src/core/node/node.ts
src/core/simulation/simulationCode.ts
src/core/simulation/simulationCodes/nest-master.code
src/core/simulation/simulationCodes/nest-v3.0.code
src/core/simulation/simulationCodes/nest-v3.1.code
src/core/simulation/simulationCodes/nest-v3.2.code
src/core/simulation/simulationCodes/nest-v3.3.code
src/core/simulation/simulationCodes/nest-v3.4.code
src/core/simulation/simulationCodes/pyNN-v0.10.code

This PR adds code template for PyNN.

Add template for PyNN

---

README.md

Add the funding information to the README.md file

README.md: Add funding information

---

src/components/project/ProjectBar.vue
src/components/simulation/SimulationCodeEditor.vue
src/core/network/networkState.ts
src/core/node/node.ts
src/core/project/project.ts
src/core/simulation/simulation.ts
src/core/simulation/simulationCode.ts
src/core/simulation/simulationCodes/cosim-v2.0.code
src/core/simulation/simulationKernel.ts

As result of hackathon. We implement code template for CoSim.

Cosim submit

---

src/background.ts
src/core/common/config.ts
src/core/model/modelDB.ts
src/core/node/nodeSpatial/freePositions.ts
src/core/project/projectDB.ts
src/core/project/projectStore.ts
src/views/AppInfo.vue

Maintain URL parses.
Additionally, it disabled starting NEST Server in Electron by default.

Maintain urls parsing

---

src/main.ts
src/registerServiceWorker.ts
vue.config.js

It uses relative path for public URL.
Closes #572

Use relative public path

---

src/components/controls/ArrayInput.vue
src/components/controls/RangeSlider.vue
src/components/controls/TickSlider.vue
src/components/controls/ValueSlider.vue

Fix auto simulation on param changes

---

src/components/node/NodeEditor.vue
src/helpers/connection/connection.ts
src/helpers/network/network.ts
src/helpers/node/node.ts
src/helpers/node/nodeView.ts
src/helpers/project/networkProject.ts
src/helpers/project/project.ts
src/helpers/simulation/simulation.ts
src/helpers/synapse/synapse.ts
src/workspaces/nest/helpers/synapse/synapse.ts

Fix minor bugs, e.g. param view or node shape for synaptic weights

---

src/components/controls/ValueSlider.vue

Fix label overlapping in slider component

---

src/helpers/activity/activities.ts
src/helpers/activity/activity.ts
src/helpers/activityGraph/activityChartGraph/activityChartGraph.ts
src/helpers/network/network.ts
src/helpers/node/node.ts
src/helpers/project/networkProject.ts

Fix adding and removing panels
