- src/components/navigation/ModelNavList.vue
- src/components/navigation/Navigation.vue
This PR simplifies the switching between the 'Model' and 'Project' view: It stores the least recently viewed model/project and selects it without any further interaction.
Before:
After:
> Navigation: Change behavior of the switch between Projects and Models

- src/components/network/NetworkGraph.vue
- src/core/network/networkGraph.ts
This changes the connector symbol slightly to indicate the function a bit clearer, as shown below. What do you think about it?
Before:
After:
> NetworkGraph: Add plus symbol to the connector

- docker-compose.yml
- src/assets/config/Connection.json
- src/assets/models/spike_generator.json
- src/assets/models/step_current_generator.json
- src/components/parameter/ParameterEdit.vue
- src/core/code.ts
- src/core/connection/connectionCode.ts
- src/core/connection/synapseCode.ts
- src/core/model/modelCode.ts
- src/core/network/networkCode.ts
- src/core/node/nodeCode.ts
- src/core/node/nodeSpatial.ts
- src/core/parameter/parameter.ts
- src/core/parameter/valueGenerator.ts
- src/core/project/projectCode.ts
- src/core/simulation/simulationCode.ts
This PR optimize parameter components and code generation.
Since NEST converts integer into float automatically (https://github.com/nest/nest-simulator/pull/2024), formatting into float in textual codes becomes obsolete.
I took the change to optimize generation algorithm for textual codes.
> No need to format parameter values to float.

- src/components/network/NetworkGraph.vue
- src/components/node/NodeChip.vue
- src/core/connection/connectionGraph.ts
- src/core/network/networkGraph.ts
- src/core/node/nodeGraph.ts
This PR restructures the network graph core component. 
Thus, NodeGraph and ConnectionGraph objects were outsourced.
initNetworkGraph and updateNetworkGraph were renamed to init and update.
> Restructure network graph

- public/config.json
- src/App.vue
- src/assets/config/NESTSimulator.json
- src/components/About.vue
- src/components/model/ModelDocumentation.vue
- src/components/navigation/ModelNavList.vue
- src/core/app.ts
- src/core/backends/backend.ts
- src/core/backends/nestSimulator.ts
- src/core/node/nodeCode.ts
- src/core/project/project.ts
- src/main.ts
- src/views/Settings.vue
This PR enables the options to change the configuration in the production.
For instance when NEST Simulator is serving at port 7000 and NEST Desktop should use this port by default.
The commits include
> External config e.g. for NEST Simulator

- src/components/network/NetworkEditor.vue
- src/core/network/networkGraph/networkGraph.ts
- src/core/node/node.ts
- src/core/node/nodeGraph/nodeGraph.ts
- src/core/node/nodeState.ts
- src/core/project/project.ts
- src/core/project/projectStore.ts
- src/core/project/projectView.ts
- src/views/Project.vue
This PR fixes the updating of the network graph when another project is loaded (`projectId` is changed).
It fixes the issue #162 and #164.
> Update network graph when a new project is loaded.

- vue.config.js
This commit adds the option to pass with an enviroment variable "CI" wheter the compile process is run in a CI environment or not (like on a personal system where other processes need resources, too).
> vue.config.js: Optimize compile performance

- vue.config.js
`cpus().length + 2` seems to generate too much stalling
> vue.config.js: Try different settings for core count

- src/components/activity/activityAnimation/ActivityAnimationController.vue
- src/components/parameter/ParameterEdit.vue
This PR adds time slider for animation controller.
The slider for current time:
> Add slider for time in animation controller

- src/core/project/projectView.ts
It fixes the bug in creating a new project. A projectId might be not existed.
> Only slice projectId if existed.

- src/components/model/ModelDocumentation.vue
- src/views/Model.vue
It fixes a small bug to show model doc.
The documentation of the model displayed in the node menu was somehow broken.
> Fix showing model doc in node menu

- package.json
It prevents to publish output to github after building electron.
> Add `-p never` for electron-builder

- src/router/index.ts
When testing in production in docker image reloading page doesn't work. 
So, I decide to use hash for router history.
> Use hash for router history

- src/assets/projects/model-f-i-curve.json
- src/core/model/modelView.ts
- src/views/Model.vue
From students feedback, it is useful to show F-I curve of neurons in NEST Desktop directly.
It depends on #280.
> Add F-I curve for neuron models

- src/core/parameter/parameter.ts
It is not necessary to convert value in float, because NEST accepts Interger.
However, in array input it accidentally converts array of a single unit into number.
As consequence parseFloat is removed.
It still works with number input as well as array input.
> Remove parseFloat

- docs/developer/preparation.rst
Introducing the hints mentioned in the 'Documentation' card of the 3.1 project.
> Docs: Add hint how to prevent freezes during compilation

- docs/reference/sections/about.rst
- docs/reference/sections/model.rst
Adds the "About" and "Model" views to the reference section (both not included in any toctree yet).
> Docs reference model about

- docs/contents.rst
- docs/developer/continuous-integration.rst
- docs/developer/index.rst
- docs/developer/production.rst
- docs/developer/semantic-version.rst
- docs/lecturer/index.rst
- docs/user/usage.rst
This PR adds/polishes some of the points which are still open in the GitHub project for NEST Desktop 3.1, namely
and multiple other fixes.
> Extend the documentation with some missing parts of v3.1

- src/App.vue
Since #310 the status of the backends is checked every 2 seconds, the iframe component becomes obsolete.
Thus it is removed.
> Remove iframe

- src/components/simulation/SimulationButton.vue
It shows `Prepare` when no `simulate()` existed in the code.
> Prepare simulation button

- src/components/model/ModelDocumentation.vue
The link should redirect to the user doc of the correct NEST version.
Closes #374.
> Correct version for model doc

- .gitlab-ci.yml
Since runners are tagged with other names, jobs in CI are stuck. 
The tags of the runners are currently `shell-runner read-only` and `docker-runner read-only`.
> Change tag for CI runner

- src/assets/config/Connection.json
- src/assets/config/Node.json
- src/assets/config/SimulationKernel.json
- src/components/project/ProjectLabBook.vue
- src/core/connection/connection.ts
- src/core/node/nodeSpatial/freePositions.ts
- src/core/node/nodeSpatial/gridPositions.ts
- src/core/node/nodeSpatial/nodeSpatial.ts
- src/core/parameter/parameter.ts
This PR clearifies the value format for parameter in the scripted simulation code in Python
For instance 
- the connection probability has to be strict float (`p=1.0`).
- `indegree` and `outdegree` are integers.
> Fix param format

- .gitlab-ci.yml
Fixes the syntax problem, which stalls the pipeline:
We might discuss to remove the `read-only` tag, since every machine has it (so it should have no impact on the selection).
> Fix regression in GitLab CI tags

- src/components/node/NodeModelSelect.vue
Then a copy model is selected in node panel, it should show no parameters.
Fixed #377
> Fixed param visibility when a copied model is selected

- src/core/activity/activity.ts
- src/core/activity/analogSignalActivity.ts
- src/core/activity/spikeActivity.ts
- src/core/project/insite/insite.ts
This PR fixed color mismatch of activities in Insite mode by sorting activities by recorder unit IDs.
Thus, I renamed `nodeCollectionId` to `recorderUnitId`.
Fixed #367
> Sort activities by recorder unit IDs in Insite mode

- src/assets/config/ModelView.json
- src/components/model/ModelDocumentation.vue
- src/components/node/NodeMenu.vue
- src/core/model/modelView.ts
- src/views/AppSettings.vue
This PR adds iframe for model documentation.
User is able to change the option to get plain text from the backend (in settings).
> Use iframe to view model documentation

- src/components/network/NetworkEditor.vue
- src/components/network/NetworkEditorToolbar.vue
- src/core/network/networkGraph/networkGraph.ts
- src/core/node/nodeGraph/nodeGraphShape.ts
This PR adds a button in the network editor. 
The user can click on button to save network graph to image file in svg format.
> Add button to export networkGraph to image file.

- .gitlab-ci.yml
- package.json
Since few weeks node 18 is the new LTS and thus causes issues in building app in gitlab CI.
We keep using node 16 but in future we will upgrade to node 18.
Additonally, I added configuration that rewrite version for Python Package.
The official semantics of npm is like `3.2.0-beta` whereas in PyPI only accepts `3.2.0b`.
> Fix gitlab CI

- vue.config.js
This PR increases the memory limit of the development server. The number of workers stays at 4, since that number seems to make no big difference for the compile time. It might be that the single-threaded tasks already take the main time.
> Increase memory limit of dev server

- src/core/model/modelStore.ts
This PR fetch models from `nest.GetKernelStatus()` because `nest.Models()` is deprecated and will be removed in the future.
> Fetch models from NEST

- src/core/simulation/simulation.ts
This PR fixes link to error messages page on user documentation.
The doc is not in the latest tag but after release.
> Fix url to error messages

- src/components/dialog/ModelsDialog.vue
- src/components/dialog/ProjectsDialog.vue
This PR adds "Select all"/"Unselect all" buttons to the model/project export and delete views, since it was very clumsy to achieve that before.
> Add "Select all"/"Unselect all" buttons to model/project export and delete views

- src/core/model/modelStore.ts
- src/core/model/modelView.ts
- src/core/project/projectStore.ts
- src/core/project/projectView.ts
This PR fixes routing issue on empty navigation list.
When user deletes all projects or all models, the router redirecting doesn't work.
Closes #459
> Fix redirecting error when nav list is empty

- src/components/network/NetworkParamToolbar.vue
This PR fixes unselecting nodes and connection when the user clicks on element type.
> Unselect nodes and connections when clicking on element type

- .gitlab-ci.yml
According to https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#pre-release-versioning, I added dot in pre release version semantics.
> Add dot for prelease

- src/components/parameter/ParameterEdit.vue
- src/core/activity/activityChart/activityChartGraph.ts
- src/core/activity/activityChart/activityChartPanelModels/firingRatePlotModel.ts
- src/core/activity/activityChart/activityChartPanelModels/senderCVISIPlotModel.ts
- src/core/activity/activityChart/activityChartPanelModels/senderMeanISIPlotModel.ts
- src/core/activity/activityChart/activityChartPanelModels/senderSpikeCountPlotModel.ts
- src/core/activity/activityChart/activityChartPanelModels/spikeCountPlotModel.ts
This PR adds a plot model for firing rate.
It is useful to measure time constant of the recurrent network.
Example projects:
https://github.com/nest-desktop/nest-desktop-projects/blob/main/network_models/recurrent_network_time_constant.json
> Add plot model for firing rate

- src/components/navigation/ProjectNavList.vue
- src/views/Project.vue
This PR fixes the bug of reload loops when
- user wants to create a new project
- the project id is not found
> Fix reload loops when user wants to create a new project

- package.json
- yarn.lock
'prettier' is used as extended base config in '.eslintrc.js'. It needs to be present for successful linting.
> Add '@vue/eslint-config-prettier' dependency

- src/components/parameter/ParameterEdit.vue
This PR fixes bug that produces NaN when user enter `1,1` 
in text area for parameters, e.g. spike times in spike generator.
> Fix regex match for number

- src/components/activity/ActivityGraph.vue
- src/core/activity/activity.ts
- src/core/activity/activityChart/activityChartPanelModels/spikeCountPlotModel.ts
- src/core/activity/activityGraph.ts
- src/core/activity/analogSignalActivity.ts
- src/core/activity/spikeActivity.ts
- src/core/project/insite/insite.ts
- src/core/project/project.ts
- src/core/project/projectStore.ts
- src/core/project/projectView.ts
- src/core/simulation/simulation.ts
This PR initially fixes empty node ids from Insite using 202 status.
Additional features were implemented.
> [BigBang] Extend Insite workflow

- src/core/node/nodeSpatial/nodeSpatial.ts
- src/core/simulation/simulationCodes/cosim-v2.0.code
- src/core/simulation/simulationCodes/nest-master.code
- src/core/simulation/simulationCodes/nest-v3.0.code
- src/core/simulation/simulationCodes/nest-v3.1.code
- src/core/simulation/simulationCodes/nest-v3.2.code
- src/core/simulation/simulationCodes/nest-v3.3.code
- src/core/simulation/simulationCodes/nest-v3.4.code
Nodes with grid positions doesn't need size in the scripted code.
> Fix code generation when node has grid positions

- src/App.vue
- src/core/app.ts
- src/core/common/backend.ts
- src/main.ts
- src/registerServiceWorker.ts
- vue.config.js
The app takes token from the url, e.g. 
- `http://localhost:54286/#?nest_server_access_token=test` (preferred) or
- `http://localhost:54286?nest_server_access_token=test`.
Then it stores access token value in localStorage and update header in axios instance.
With this method, the request can be authorized by the nest server backend.
Additional feature: 
It also takes NEST Server URL from the query:
- `http://localhost:54286/#?nest_server_url=http://localhost:52425`
> Access token to authorize requests to backends.
